#####################################################
##             		Rules                      ##
#####################################################
FIELD_DIR=field_dist
GRID_DIR=gridpoints

clean:
	rm -f ${OBJS} *.o *.dat
	rm -rf ${FIELD_DIR}/*.dat
	rm -rf ${GRID_DIR}/*.dat
